version: "2"
services:
  nginx:
    build: nginx/
    ports:
      - 80:80
    depends_on:
      - server
    volumes:
      - /var/log/nginx/

  server:
    build: JassServer/
    env_file:
      - ./prod.env
    depends_on:
      - redis
    volumes:
      - /JassServer/logs/

  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes

  graphplotter:
    build: PlotServer/
    volumes:
      - /plots:/plots

